### ISSUE TITLE
Building instructions?

### ISSUE THREAD

**Issue by dag7dev** [michaelchen21/gba-ddr#1]
Hi!
I discovered your repo some minutes ago, instructions on how to build the source files?
Due to the absence of screenshots, I can't tell about the game, the concept seems to be cool!

Thanks!

**Comment by ML-Chen** [comment]
Hey, I'll be adding GIFs shortly!

You could try out the following commands in Ubuntu:
```
sudo add-apt-repository ppa:tricksterguy87/ppa-gt-cs2110
sudo apt update
sudo apt install gcc-arm-none-eabi cs2110-vbam-sdl mednafen cs2110-gba-linker-script nin10kit
```
and then run `make emu`

However, mednafen seems a bit buggy, and I was only able to build this in a Docker file specific to the class I did this project for.

I used [nin10kit](https://github.com/TricksterGuy/nin10kit) for converting images to C arrays.

**Comment by ML-Chen** [comment]
I've updated the readme with build instructions ~~that get you up to the start screen, but you can't start gameplay because none of the buttons seem to be registered~~.

Basically, run the following commands:
```bash
sudo add-apt-repository ppa:sergio-br2/vbam-trunk
sudo apt update
sudo apt install vbam-sdl vbam
```

`cd` to the appropriate directory, and then run `make vba` or `vbam Game.gba`.

**Comment by dag7dev** [comment]
Thank you! I will definitely give it a try!
